version: "3"
services:
  www:
    build: .
    entrypoint: ./cmd/www/www
#    ports:
#      - "5000:5000"
    expose:
      - "5000"
    links:
      - api
    env_file:
      - .env
  api:
    build: .
    entrypoint: ./cmd/api/api
    ports:
      - "8080:8080"
#    expose:
#      - "8080"
    links:
      - geo
      - profile
      - rate
    env_file:
      - .env
  geo:
    build: .
    entrypoint: ./cmd/geo/geo
    env_file:
      - .env
  profile:
    build: .
    entrypoint: ./cmd/profile/profile
    env_file:
      - .env
  rate:
    build: .
    entrypoint: ./cmd/rate/rate
    env_file:
      - .env
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - www
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

