version: "3"
services:
  www:
    image: workshop_www
    entrypoint: ./cmd/www/www
    ports:
      - "5000:5000"
    deploy:
      replicas: 2

  api:
    image: workshop_api
    entrypoint: ./cmd/api/api
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      
  geo:
    image: workshop_geo
    entrypoint: ./cmd/geo/geo
  profile:
    image: workshop_profile
    entrypoint: ./cmd/profile/profile
  rate:
    image: workshop_rate
    entrypoint: ./cmd/rate/rate

